### PR TITLE
Implemented gatsby-plugin-preload-fonts

### PR DESCRIPTION
**Pull request by w3bdesign**
Setup and installed gatsby-preload-fonts.

Ran "npm run gatsby-preload-fonts" and added the generated font-preload-cache.json to source folder.

Check out https://www.gatsbyjs.com/plugins/gatsby-plugin-preload-fonts/

Also added typeface imports to gatsby-ssr.js

For reference, please see https://github.com/gatsbyjs/gatsby/pull/14608

### CODE REVIEW

**Comment by thundermiracle** [comment]
@w3bdesign 
Thanks for your PR.
But it seems that FOUC problem is not solved after trying this source in my PC, any idea?

**Comment by w3bdesign** [comment]
> 
> 
> @w3bdesign
> Thanks for your PR.
> But it seems that FOUC problem is not solved after trying this source in my PC, any idea?

@thundermiracle 

I didn't notice any FOUC during initial load, but if you gave me more details, I can try to debug and troubleshoot the issue.

**Comment by thundermiracle** [comment]
@w3bdesign 
I think I found the why. 
After running `gatsby build`, the following `preload fonts` parts are not exist in the compiled index.html.
And running `gatsby serve` to check the result, FOUC is still exist.

```html
<link rel="preload" as="font" href="/static/xxxxxxxxxxxxxx.woff2">
```

Would you please tell me the correct compilation steps?

**Comment by w3bdesign** [comment]
I just did a `gatsby build`and `gatsby serve` and I don't see the preload, but I see the fonts are loaded from static assets, like:

`,url(/static/droid-serif-latin-400-0161c227f906d426b759cc1326a38215.woff2)`

Also I still don't see any FOUC.

**Comment by thundermiracle** [comment]
@w3bdesign 
`url(/static/droid-serif-latin-400-0161c227f906d426b759cc1326a38215.woff2)` in css is generated because we're using `typeface-xxxx` packages which are compiled locally instead of downloading from CDN after page loaded.

`gatsby-plugin-preload-fonts` is the one which is responsible for inject `preload` parts to prevent FOUC.
As plugin's instruction:
image

I don't understand why this PR is closed & deleted, but anyway, thank you very much!

**Comment by w3bdesign** [comment]
@thundermiracle 

Sorry, I closed this because I need to prioritize my own projects in the near future and didn't want to give you the impression I was working more on it.

However, I did a little more research, and I believe a possible solution may be the following:

1. Copy the fonts being used (they are in the public folder after you do `gatsby build`) and include them in the project folder
2. Do the same with the google-fonts.css file(s).
3. Edit `gatsby-ssr.js`and implement the code from the plugin (the preload part)

I don't have time to do this myself in the near future, but if you know a bit of Javascript and Gatsby, this shouldn't be too difficult!

**Comment by thundermiracle** [comment]
@w3bdesign 
I really appreciate that you cost a lot of time on this tiny starter.
github is my hobby as well as this gatsby starter, but they're not my job which is the same as you I think.


> but if you know a bit of Javascript and Gatsby, this shouldn't be too difficult!

I did some research, I compared the source code of gatsby-plugin-preload-fonts with gatsby-plugin-google-prefetch-fonts, but didn't get the answer, so I reported an issue in the gatsby which means that I'm not the one who knows a bit of JS & gatsby.

I'll left a need help issue for whom has time or familiar with gatsby-plugin-preload-fonts.

And I think I need explain to you why this PR is not merged immediately.
1. `yarn.lock` is not updated after new library `gatsby-plugin-preload-fonts` is added 
2. `font-preload-cache.json` is not correctly generated
3. the **MOST IMPORTANT** one is that I tried this solution in another gatsby project & deployed it in staging environment but FOUC remained

This PR is closed so it means both of us don't want to involve in it anymore. Let anybody else to solve it in future if necessary.
Thanks again.

**Pull request closed without merging**
